version = 0.1
[dev.deploy.parameters]
stack_name = "Quiz-App"
resolve_s3 = true
s3_prefix = "Quiz-App"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "Environment=\"dev\""
image_repositories = []
