AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment: 
    Type: "String"
    Default: "dev"

Globals: 
  Function: 
    Timeout: 10
    Runtime: nodejs18.x
    Handler: index.lambdaHandler
    Architectures: 
      - x86_64
    Layers: 
      - !Ref Core

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: QuizApp
      Cors: 
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  
  # Layers of code  
  Core:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodejs
      ContentUri: layers/

  # Lambda Functions for API Calls
  LoginUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: LoginUser
      CodeUri: functions/quiz-account-login/
      # Layers: 
      #   - !Ref Core1
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        APICall:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: get
            RestApiId: !Ref ApiGateway
