AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: "String"
    Default: "dev"

  CognitoClientID:
    Type: "String"
    Default: ""

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Handler: index.lambdaHandler
    Architectures:
      - x86_64
    Layers:
      - !Ref Core

Resources:
  #User pool resources
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub QuizApp-${Environment}
      UsernameAttributes:
        - email
        - phone_number
      Schema:
        - Name: "email"
          Required: true
          Mutable: true

      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  # API Gateway for calls
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: QuizApp
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Layers of code
  Core:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodejs
      ContentUri: layers/

  # Lambda Functions for API Calls
  LoginUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: LoginUser
      CodeUri: functions/quiz-account-login/
      Policies:
        - AmazonCognitoPowerUser
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CognitoClientID: !Ref CognitoClientID
      Events:
        APICall:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: post
            RestApiId: !Ref ApiGateway
